### ISSUE TITLE
Annotating nested structs

### ISSUE THREAD

**Issue by bjohannesmeyer** [imdea-software/verifying-constant-time#2]
Is it possible to annotate the fields of a nested struct without recreating the struct in the wrapper function? 

For example, in the OpenSSL example's `tls1_cbc_remove_padding_wrapper` [here](https://github.com/imdea-software/verifying-constant-time/blob/master/examples/openssl/tls1_cbc_remove_padding_wrapper.c#L36), a pointer to the `SSL s_obj` struct is passed to `tls1_cbc_remove_padding`. `s_obj` contains pointers to other structs, i.e. `EVP_CIPHER_CTX cipher_ctx` and `SSL3_STATE s3_obj`. Then these structs may also contain pointers to other structs, and so on. However, all of these structs are created in the wrapper, using either hardcoded values (e.g. 0, NULL) or values passed as parameters to the wrapper. Would it be possible to simply have the top-level struct (e.g. `SSL *s`) be a parameter to the wrapper, and then annotate fields within that struct?

When I try to do this, I'm running into errors (there's also a chance that I'm implementing this incorrectly). Take for example the following code. `func` takes a pointer to a `foo` struct, which contains a pointer to a `bar` struct. The pointers to the `foo` and the `bar` are public, so `func`'s branch on the `bar` pointer should be verified as constant-time. 

```
#include "ct-verif.h"

struct bar {int z;};
struct foo {struct bar *y;};

void func(struct foo* x) {
  int i;
  if(x->y) i=9*7;
}

void func_wrapper(struct foo* x) {
  public_in(__SMACK_value(x));
  public_in(__SMACK_value(x->y));
  func(x);
}
```

However this gives me the following error: 
```
Generating BPL model
smack.py -t  --verifier=boogie --entry-points func_wrapper --unroll 1 --loop-limit 1 -bpl /root/c-verifs/structs-minimal.bpl  /root/c-verifs/structs-minimal.c
SMACK program verifier version 1.5.1
SMACK generated /root/c-verifs/structs-minimal.bpl
Generating product program
ruby -I`which bam | sed s/.......$//`/lib `which bam | sed s/.......$//`/bin/bam --shadowing /root/c-verifs/structs-minimal.bpl -o /root/c-verifs/structs-minimal-instrumented.bpl
BAM! BAM! Boogieman version 1.0-63-g82062a3
                    copyright (c) 2015, Michael Emmi

Warning: could not resolve constant/variable $load.i0
Verifying product program for constant-time violations
boogie /doModSetAnalysis /root/c-verifs/structs-minimal-instrumented.bpl
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
/root/c-verifs/structs-minimal-instrumented.bpl(213,10): Error: use of undeclared function: $load.i0
/root/c-verifs/structs-minimal-instrumented.bpl(213,30): Error: use of undeclared function: $load.i0
2 name resolution errors detected in /root/c-verifs/structs-minimal-instrumented.bpl
```

However when I create the structs within the wrapper (using the same approach as `tls1_cbc_remove_padding_wrapper`), it verifies. That is, replace `func_wrapper` with the following:
```
void func_wrapper(int c) {
  struct bar b = {c};
  struct foo a = {&b};
  func(&a);
}
```

Is there a more convenient way of annotating nested structs without recreating them within the wrapper (like I was going for above)? Any idea what is causing the error above?

**Comment by michael-emmi** [comment]
Hey @bjohannesmeyer looks like you’re using a very old version of Smack; we’re currently at 1.9.0. I’ve just pushed a fix for the Smack part of this problem, although this may lead to another issue in Bam eventually. Can you update, try again, and see where we’re at?

**Comment by bjohannesmeyer** [comment]
Sorry for the delay. Just as you expected, updating my tools fixed the SMACK problem (I no longer get the error above from nested structs). However, now everything seems to verify --- even code that shouldn't. For example, the following should not verify since `x` is secret:

```
#include "ct-verif.h"

void foo(int x) {
        int a;
        if(x == 3) a = 9*7;
}

void foo_wrapper(int x) {
        foo(x);
}
```

However, after updating my tools, it is erroneously verifying:
```
Generating BPL model
smack -t  --verifier=boogie --entry-points foo_wrapper --unroll 1 --loop-limit 1 -bpl /root/verifying-constant-time/examples/foo/foo.bpl  /root/verifying-constant-time/examples/foo/foo.c
SMACK program verifier version 1.9.0
SMACK generated /root/verifying-constant-time/examples/foo/foo.bpl
Generating product program
ruby -I`which bam | sed s/.......$//`/lib `which bam | sed s/.......$//`/bin/bam --shadowing /root/verifying-constant-time/examples/foo/foo.bpl -o /root/verifying-constant-time/examples/foo/foo-instrumented.bpl
BAM! BAM! Boogieman version 1.0.6
                    copyright (c) 2015, Michael Emmi

Verifying product program for constant-time violations
boogie /doModSetAnalysis /root/verifying-constant-time/examples/foo/foo-instrumented.bpl
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 1 verified, 0 errors
```
The tool versions I'm now using are: 
- SMACK 1.9.0
- Bam 1.0.6
- Z3 4.7.0
- Boogie 2.3.0.61016

FWIW the program successfully _does not_ verify when I use the old versions of the tools (the versions pointed at by the submodules in the `tools` directory). That is:
- SMACK 1.5.1
- Bam 1.0-63-g82062a3
- Z3 4.4.0
- Boogie 2.3.0.61016

**Comment by michael-emmi** [comment]
Ok so there are a few things going on here. First, you should be using the latest version of all tools — the old versions, and that repository set up with submodules, was formerly maintained by @fdupress, but is no longer maintained.

Second, during an integration of some work done at Amazon, the interface to the `--shadowing` flag has changed a bit. From what I can tell, this is how it should be invoked at the moment:
````
bam a.bpl --shadowing self_comp_mode=selective,branchcond_assertion=assert_shadow_ok,memory_assertion=assert_shadow_ok -o b.bpl
````
While this interface does seem unfortunate, I haven’t had time to fix it.

Third, there’s now a better way to invoke bam as a Boogie-code post-processor as part of Smack; see here: https://github.com/michael-emmi/ctverif/blob/master/lib/index.js#L15

Lastly, since there are now a few different people trying to use ct-verif in various ways, I thought it might be good to at least converge on a consistent invocation strategy. At some point I had created this repository for that purpose:

https://github.com/michael-emmi/ctverif

The idea was to require having the latest versions of Smack and Bam installed separately, and then this script would just tie them together. Given recent developments, this is not fully up to date, but it would probably be best that we work to fix that.

**Comment by michael-emmi** [comment]
Also, apologies for any difficulties: neither @fdupress nor myself have had much time to maintain this recently.

**Comment by bjohannesmeyer** [comment]
No worries. Thanks for the links. I'll

**Comment by bjohannesmeyer** [comment]
(oops, I didn't mean to close the issue)

No worries. Thanks for the info. I will give it a try with the newer ctverif repo you've linked.

**Comment by bjohannesmeyer** [comment]
Updating tools and using https://github.com/michael-emmi/ctverif fixes this.
