### ISSUE TITLE
example Makefiles not working

### ISSUE THREAD

**Issue by ghost** [imdea-software/verifying-constant-time#4]
The example "sort" works in the bin Makefile, but when I try to run a different example Makefile(such as mee-cbc, or sort in the examples), I get the following:

> Verifying product program for constant-time violations
boogie /doModSetAnalysis /home/vagrant/verifying-constant-time/examples/sort/sort-instrumented.bpl
make[1]: boogie: Command not found
make[1]: *** [verify] Error 127
make[1]: Leaving directory `/home/vagrant/verifying-constant-time/bin'
make: *** [verify] Error 2

I tried changing `WD` to ../examples/sort but it did not help.  Again, the program works perfectly when I manually enter my `WD`, `EXAMPLE` and `ENTRYPOINTS` into the `bin` Makefile.

**Comment by ghost** [comment]
I am very unfamiliar with Makefiles... I found the issue.  They are simply incomplete.  `WD`, `SMACKPATH`, `BAMPATH`, and `BOOGIEPATH` need to be modified.

**Comment by Luweicai** [comment]
Hello，I come across the same question like you. I am not very clear about what you have done to solve the problem. Do you mean that copy the bin Makefile then paste it under the examples file like mee-cbc then modeify the WD, SMACKPATH, BAMPATH and BOOGIEPATH?
